services:
  rates:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rates
    env_file: .env
    environment:
      DB_TYPE: postgres
      DB_HOST: rates-postgres
      DB_PORT: 5432 # Ichki port, PostgreSQL uchun default port
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - '127.0.0.1:${PORT}:${PORT}' # Tashqi port:same, ichki port: same
    volumes:
      - ./assets:/app/assets # Mount local `assets` to container `/app/assets`
      - ./uploads:/app/uploads # Optional: if you use `/uploads` for file storage
    networks:
      - app_network
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: rates-postgres
    image: postgres:16-alpine
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent volume
    ports:
      - '${DB_PORT}:5432' # Tashqi port 5999, ichki port 5432
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge # Custom network for communication between services

volumes:
  postgres_data: # Persistent volume for PostgreSQL data
